[package]
name = "backend"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "backend"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
derive_more = {version = "2.0.1", features=["from"]}
fnv = "1.0.7"
lambdaworks-groth16 = {  git="https://github.com/lambdaclass/lambdaworks.git",version = "0.11.0"}
lambdaworks-math = { git="https://github.com/lambdaclass/lambdaworks.git", version = "0.11.0" }

# lambdaworks-math = { workspace = true, features = ["lambdaworks-serde-string"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.11"
tokio = "1.43.0"
wasmer = "5.0.0"
wasmer-wasix = "0.33.0"
# bincode = { version = "2.0.0-rc.2", tag = "v2.0.0-rc.2", git = "https://github.com/bincode-org/bincode.git", features= ['serde'] }
ndarray = { version = "0.16.1", default-features = false }
zkp-rust-tools-math = { workspace = true, features = ["alloc"] }
