
[package]
name = "zkp-rust-tools-math"

[dependencies]
icicle-runtime = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.3.0" }
icicle-core = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.3.0" }
icicle-bls12-377 = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.3.0"}
icicle-bls12-381 = { git = "https://github.com/ingonyama-zk/icicle.git", tag = "v3.3.0" }

